name: CI - Build and Push to ECR

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-push:
    name: Build and Push Microservices
    runs-on: ubuntu-latest
    # ESSENCIAL: Declarar o environment onde as chaves estão (conforme sua imagem)
    environment: AWS 

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and Push Images
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          # Lista atualizada com o sufixo "-main" conforme imagem do repositório
          SERVICES=("auth" "flag" "targeting" "evaluation" "analytics")
          
          for SERVICE in "${SERVICES[@]}"; do
            echo "Building $SERVICE service..."
            
            REPO_NAME="togglemaster-$SERVICE"
            
            # Ajustado para o caminho exato das suas pastas: ./nome-service-main
            docker build -t $ECR_REGISTRY/$REPO_NAME:latest ./$SERVICE-service-main
            
            docker push $ECR_REGISTRY/$REPO_NAME:latest
            
            echo "Pushed $SERVICE to ECR successfully."
          done