name: CI - Build and Push to ECR

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-push:
    name: Build and Push Microservices
    runs-on: ubuntu-latest
    environment: AWS 

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and Push Images
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          # Gera o hash curto do commit (7 caracteres)
          VERSION="v1.0.0-$(echo ${{ github.sha }} | cut -c1-7)"
          echo "Version to be used: $VERSION"

          SERVICES=("auth" "flag" "targeting" "evaluation" "analytics")
          
          for SERVICE in "${SERVICES[@]}"; do
            echo "Building $SERVICE service..."
            REPO_NAME="togglemaster-$SERVICE"
            
            # Build com duas tags: a específica do commit e a 'latest' para facilitar testes
            docker build -t $ECR_REGISTRY/$REPO_NAME:$VERSION \
                         -t $ECR_REGISTRY/$REPO_NAME:latest \
                         ./$SERVICE-service-main
            
            # Push de ambas as tags
            docker push $ECR_REGISTRY/$REPO_NAME:$VERSION
            docker push $ECR_REGISTRY/$REPO_NAME:latest
            
            echo "Pushed $SERVICE version $VERSION to ECR."
          done