name: CI - Build, Push and Update GitOps

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-push:
    name: Build and Push Microservices
    runs-on: ubuntu-latest
   
    steps:
      - name: Checkout Application Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and Push Images
        id: build-images
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          # Gera a tag baseada no commit hash curto
          VERSION="v1.0.0-$(echo ${{ github.sha }} | cut -c1-7)"
          SERVICES=("auth" "flag" "targeting" "evaluation" "analytics")
          
          for SERVICE in "${SERVICES[@]}"; do
            REPO_NAME="togglemaster-$SERVICE"
            echo "Building $SERVICE..."
            docker build -t $ECR_REGISTRY/$REPO_NAME:$VERSION ./$SERVICE-service-main
            docker push $ECR_REGISTRY/$REPO_NAME:$VERSION
          done
          # Salva a versão no ambiente para os próximos passos
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      # --- CONEXÃO COM O REPOSITÓRIO GITOPS ---

      - name: Checkout GitOps Repo
        uses: actions/checkout@v4
        with:
          repository: fdaltro/togglemaster-gitops
          token: ${{ secrets.GIT_TOKEN }} # Usando seu segredo já configurado
          path: gitops-repo

      - name: Update Kustomize Tags
        run: |
          VERSION=${{ env.VERSION }}
          ECR_REGISTRY=${{ steps.login-ecr.outputs.registry }}
          SERVICES=("auth" "flag" "targeting" "evaluation" "analytics")
          
          # Entra na pasta onde estão as configurações de apps
          cd gitops-repo/apps
          
          for SERVICE in "${SERVICES[@]}"; do
            echo "Atualizando manifestos de $SERVICE para a versão $VERSION"
            cd $SERVICE
            # O kustomize edit troca a tag no arquivo kustomization.yaml automaticamente
            # O 'togglemaster-$SERVICE' é a chave fixa que está no deployment.yaml
            # O '$ECR_REGISTRY/togglemaster-$SERVICE:$VERSION' é o valor dinâmico da AWS
            kustomize edit set image togglemaster-$SERVICE=$ECR_REGISTRY/togglemaster-$SERVICE:$VERSION
            cd ..
          done

      - name: Commit and Push to GitOps Repo
        run: |
          cd gitops-repo
          git config --global user.email "fabriciodaltro@gmail.com"
          git config --global user.name "fdaltro"
          git add .
          git commit -m "chore: deploy version ${{ env.VERSION }} [skip ci]" || echo "Sem mudanças"
          git push origin main