name: ToggleMaster Master Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  # ==========================================
  # ESTÁGIO 1: LINTING (QUALIDADE DE CÓDIGO)
  # ==========================================
  lint-go:
    name: Lint Go
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [auth-service-main, evaluation-service-main]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.21'
      - name: Dependencies
        working-directory: ./${{ matrix.service }}
        run: |
          if [ ! -f go.mod ]; then go mod init ${{ matrix.service }}; fi
          go mod tidy
      - name: Linter
        uses: golangci/golangci-lint-action@v6
        with:
          version: latest
          working-directory: ${{ matrix.service }}
          args: --timeout=5m --allow-parallel-runners --disable errcheck,staticcheck

  lint-python:
    name: Lint Python
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [flag-service-main, targeting-service-main, analytics-service-main]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.9'
      - name: Linting
        working-directory: ./${{ matrix.service }}
        run: |
          python -m pip install --upgrade pip
          pip install flake8
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics

  # ==========================================
  # ESTÁGIO 2: SCA (SEGURANÇA DE DEPENDÊNCIAS)
  # ==========================================
  sca-scan:
    name: SCA Scan (Trivy)
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [auth-service-main, evaluation-service-main, flag-service-main, targeting-service-main, analytics-service-main]
    steps:
      - uses: actions/checkout@v4
      - name: Run Trivy SCA
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          scan-ref: './${{ matrix.service }}'
          format: 'table'
          # '0' permite que o deploy continue mesmo com vulnerabilidades para fins de demo
          exit-code: '1' 
          severity: 'CRITICAL'

# ==========================================
  # ESTÁGIO 3: SAST (SEGURANÇA DO CÓDIGO FONTE)
  # ==========================================
  sast-scan:
    name: SAST Scan (Semgrep)
    runs-on: ubuntu-latest
    # Mantemos o paralelismo para os 5 serviços
    strategy:
      fail-fast: false
      matrix:
        service: [auth-service-main, evaluation-service-main, flag-service-main, targeting-service-main, analytics-service-main]
    
    steps:
      - name: Checkout Código
        uses: actions/checkout@v4

      - name: Instalar Python para o Semgrep
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Executar Semgrep CI
        run: |
          python3 -m pip install semgrep
          # Usamos a flag --subdir para focar na pasta do microserviço atual da matrix
          semgrep ci \
            --config p/default \
            --config p/security-audit \
            --config p/secrets \
            --subdir ./${{ matrix.service }}


  # ==========================================
  # ESTÁGIO 4: UNIT TESTS (LÓGICA)
  # ==========================================
  test-go:
    name: Unit Test Go
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [auth-service-main, evaluation-service-main]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.21'
      - name: Run Tests
        working-directory: ./${{ matrix.service }}
        run: |
          if [ ! -f go.mod ]; then go mod init ${{ matrix.service }}; fi
          go mod tidy
          go test -v ./...

  test-python:
    name: Unit Test Python
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [flag-service-main, targeting-service-main, analytics-service-main]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
      - name: Run Tests
        working-directory: ./${{ matrix.service }}
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          pytest || echo "Sem testes definidos"

  # ==========================================
  # ESTÁGIO 5: BUILD, PUSH & GITOPS DEPLOY
  # ==========================================
  deploy:
    name: Build & Deploy to EKS
    # O Deploy espera o sucesso de TODOS os jobs de teste e segurança
    needs: [lint-go, lint-python, sca-scan, sast-scan, test-go, test-python]
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    
    steps:
      - name: Checkout Application Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and Push Images
        id: build-images
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          VERSION="v1.0.0-$(echo ${{ github.sha }} | cut -c1-7)"
          SERVICES=("auth" "flag" "targeting" "evaluation" "analytics")
          
          for SERVICE in "${SERVICES[@]}"; do
            REPO_NAME="togglemaster-$SERVICE"
            echo "Building image for $SERVICE..."
            docker build -t $ECR_REGISTRY/$REPO_NAME:$VERSION ./$SERVICE-service-main
            docker push $ECR_REGISTRY/$REPO_NAME:$VERSION
          done
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Checkout GitOps Repo
        uses: actions/checkout@v4
        with:
          repository: fdaltro/togglemaster-gitops
          token: ${{ secrets.GIT_TOKEN }}
          path: gitops-repo

      - name: Update Kustomize Tags
        run: |
          VERSION=${{ env.VERSION }}
          ECR_REGISTRY=${{ steps.login-ecr.outputs.registry }}
          SERVICES=("auth" "flag" "targeting" "evaluation" "analytics")
          
          cd gitops-repo/apps
          
          for SERVICE in "${SERVICES[@]}"; do
            echo "Updating anchor 'togglemaster-$SERVICE' to version $VERSION"
            cd $SERVICE
            kustomize edit set image togglemaster-$SERVICE=$ECR_REGISTRY/togglemaster-$SERVICE:$VERSION
            cd ..
          done

      - name: Commit and Push to GitOps Repo
        run: |
          cd gitops-repo
          git config --global user.email "fabriciodaltro@gmail.com"
          git config --global user.name "fdaltro"
          git add .
          git commit -m "chore: deploy version ${{ env.VERSION }} [skip ci]" || echo "No changes"
          git push origin main